.Dd $Mdocdate: July 31 2018 $
.Dt INPUT 1
.Os
.Sh NAME
.Nm input
.Nd interactively prompt for user input
.Sh SYNOPSIS
.Nm input
.Op Fl t
.Op Fl c Ar completions
.Op Fl p Ar prompt
.Op Fl h Ar file
.Op Fl s Ar size
.Sh DESCRIPTION
The
.Nm
utility interactively prompts for input lines.
In demarcation to
.Xr read 1
it provides readline-like line editing and an optional persistent
history.
Besides it continuously prompts for input instead of waiting for a
single input line.
.Pp
If standard input is not a
.Xr tty 4
.Nm
behaves like
.Xr read 1 .
Meaning it reads only a single line from standard input.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl t
Force reading from
.Xr tty 4
instead of standard input.
.It Fl c Ar completions
Read completions from the file
.Ar completions .
The file should contain one completion per line.
It is currently filtered using
.Xr grep 1 .
.It Fl p Ar prompt
Change the default prompt string
.Qq "> "
to
.Ar prompt .
.It Fl h Ar file
Store the editing history in
.Ar file .
By default no editing history is kept.
.It Fl s Ar size
Specify the maximum editing history size, by default 256 entries are kept.
.El
.Sh EXAMPLES
To write all input entered by the user to a file using a shell script:
.Bd -literal -offset indent
	input | while read line; do
		echo "${input}" >> somefile.txt
	done
.Ed
.Sh SEE ALSO
.Xr rlwrap 1
.Sh AUTHORS
.An Sören Tempel Aq Mt soeren@soeren-tempel.net
.Sh BUGS
It is currently not possible to complete input containing a single
quote.
